grafana:
  adminPassword: polycode-grafana
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts:
      - grafana.staging.polycode.do-2021.fr
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.staging.polycode.do-2021.fr
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: scrape-city-api
        static_configs:
          - targets: ["hello-rust-rust-tp-cicd/metrics"]
