name: "CI"

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and push to docker.io
    runs-on: ubuntu-latest
    steps:
      - name: Fetch git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install gitversion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: "5.x"
      - name: Run gitversion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - name: Format gitversion output
        id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.shortSha }}"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Use dependencies cache
        uses: Swatinem/rust-cache@v1
      - name: Build and package release application
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Build and push the docker image
        uses: docker/build-push-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: slucido/hello-world-rust
          tags: ${{ steps.version.outputs.version }}
          addLatest: true
