name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  build_and_push:
    name: Build and push to docker.io
    runs-on: ubuntu-latest
    steps:
      - name: Fetch git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1
      - name: Install gitversion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: "5.x"
      - name: Run gitversion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
      - name: Format gitversion output
        id: version
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}"
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Use dependencies cache
        uses: Swatinem/rust-cache@v1
      - name: Build and package release application
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: slucido/city-api:${{ steps.version.outputs.version }}, slucido/city-api:latest
